### ISSUE TITLE
BTC Relay integration

### ISSUE THREAD

**Issue by c055** [OasisDEX/oasis#10]
@rainbeam:

>  BTC relay is now on mainnet. In principle we can make use of it in Maker Market, to allow BTC as a trading token.
> 
> https://github.com/ethereum/btcrelay
> 
> btc-relay provides an incentive layer for the publication of Bitcoin block header information to the Ethereum blockchain, acting as a SPV client. This means that we can verify whether a specific bitcoin transaction has taken place. As it is, btc-relay does not enable a BTC token, only transaction verification. In this sense it is read only. 
> 
> The btc relay api provides a useful method for us:
> 
> ```
> relayTx(rawTransaction, transactionIndex, merkleSibling, blockHash, contractAddress)
> ```
> 
> Where `contractAddress` is an external contract that will be called (a Market endpoint). The rest is transaction related stuff. This could all come from the user, but that would require them to be running a node. Alternatively the user can just provide a tx hash, from which the rest can be derived by using an external source.
> 
> Proposed use case:
> 1. Seller creates Offer (sell TOKEN for BTC sent to BtcAddress)
> 2. Offer goes into OrderBook (maybe separate to regular erc20 orderbook)
> 3. Buyer accepts Offer. Offer is locked.
> 4. show modal to Buyer: "Send btc to BtcAddress, enter tx hash after 6 confirmations"
> 5. Buyer enters tx hash. Frontend gets transaction, e.g. from blockr.io, contructs merkle proof and calls relayTx
> 6. on relayTx success, TOKEN is transferred to Buyer, Offer closed
> 7. on relayTx failure / no tx entered before Timeout (1.5h?), TOKEN released back to Seller, Offer unlocked.
> 
> All the user is required to do is send BTC and then provide the tx hash after 6 confirmations.
> 
> Problems:
> 1. _Transaction takes a long time_. btc-relay requires _6_ confirmations. I think this is ok as long as traders know about it. Might speed up in future. The real problem here is that Bitcoin is slow.
> 2. _Reliance on external API._ We need this to avoid the user having to supply the full tx info, rather than just the hash. We don't need to trust the provider of that info. This could be turned into a Keeper task.

[ BTC Relay integration #87 ](https://github.com/MakerDAO/maker-otc/issues/87)

**Comment by cassiopaia** [comment]
@rainbeam referenced: 

https://github.com/MakerDAO/maker-otc/issues/87

**Comment by pimato** [comment]
project is on hold, so will close it for now.
