### ISSUE TITLE
Create an API endpoint that exposes 24h trade volume and last price for each coin

### ISSUE THREAD

**Issue by Rune23** [OasisDEX/oasis#107]
This is maybe already possible with the market data website daniel has made?

**Comment by Rune23** [comment]
This is what CMCs request form say is needed

"Please provide a link to the API documentation (Required for listing) *
It needs to expose the 24h trade volume and the last price for each coin (For example, Poloniex's API endpoint: https://poloniex.com/public?command=returnTicker)"

**Comment by pimato** [comment]
introduced with : 
https://api.mkr.market/

**Comment by ItsmeJulian** [comment]
@pimato  is this still the way to go, meaning new pairs will be available on this api endpoint? is there an doc listing the api interface?
