### ISSUE TITLE
order confirmation warning color

### ISSUE THREAD

**Issue by seriouslylost** [OasisDEX/oasis#110]
hi!

At the moment the 'order confirmation window' pops up no matter what.
How about:   
 it only pops up if you have entered a price on a buy order higher than that of an existing sell order? (and vice versa) This will be important once bots are present that can bounce on orders.

if the window always pops up users will just ignore it. if it only pops up sometimes (with red bold text) users may actually read what it says

**Comment by pimato** [comment]
This is something I wouldn't do, because a user will ask himself why is the modal not popping up all the time ? The outcome of this will be, that the user needs to learn this kind of distinction, and we don't want that. Our aim is to provide the simplest, best Experience without much learning.

**Comment by seriouslylost** [comment]
ok


________________________________
