### ISSUE TITLE
Information regarding AUTOMATIC MATCHING BETWEEN ORDERS

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#128]
I copy the message from the MakerChat : 

It's becoming a very common thing now to see *newcomers getting confused by the lack of order matching*. And this is our fault, this should be very explicit because there's _not a single centralized exchange_ which works this way. I suggest a warning msg below the buy/sell boxes and above the "buy orders" and "sell order" boxes.

**Suggestions for this message *below the buy/sell* boxes:**

>THERE'S NO AUTOMATIC MATCHING BETWEEN ORDERS!
>To create a new entry on the order book, simply use the boxes above. But if you want to fill existing orders, *you have to click on each desired order, one at a time*.
There should be a little `x` at the right top corner of the message box, so the user can dismiss it (hide it) after having read it.

**Comment by pimato** [comment]
I will create a few different approaches so we can decide together how we get the user informed regarding the missing automatic matching between orders!

**Comment by pimato** [comment]
**Version 1** 

![bildschirmfoto 2017-01-22 um 11 57 09](https://cloud.githubusercontent.com/assets/5337809/22181999/fdfdf74a-e099-11e6-9cce-bcdbcbf3be36.png)

**Version 2**

![bildschirmfoto 2017-01-22 um 11 56 55](https://cloud.githubusercontent.com/assets/5337809/22182000/04b3473e-e09a-11e6-803a-bee2bcd13675.png)

**Comment by Rune23** [comment]
I prefer version 1

**Comment by Rune23** [comment]
under get started 3) there is a typo: befor -> before.

There also need to be an additional sentence, something like "You're automatically prompted to do this if your allowance isn't already set"

**Comment by Rune23** [comment]
btw lets get rid of the numbers for allowance and just make it a binary approval mechanism that sets the allowance to 999999999 behind the scenes.

**Comment by jorisbontje** [comment]
I disagree to setting allowance to some arbitrary high number under the
hood for convenience sake. please keep security in mind at all time; I have
heard a couple times of traders being saved from making incorrect trades
due to the allowance mechanism.

**Comment by pimato** [comment]
Version I is updated:

@Rune23 

![bildschirmfoto 2017-01-24 um 12 30 36](https://cloud.githubusercontent.com/assets/5337809/22245604/04aa9466-e231-11e6-99f2-a79b8b63a169.png)

I made your suggested sentence a little bit shorter so it can fits in one line. Do you think this is enough ? Do you have maybe a better idea?

Regarding the allowance thing. I think we should discuss this topic with the whole team and should be moving it to the next design iteration. Right now we should clean most of the issues we already have and make the UX as perfect as possible.

**Comment by gbalabasquer** [comment]
@pimato What happens if you close one of the banners? How the other would show?

**Comment by pimato** [comment]
if you close the left one, the right one should be expand (and so on) example:

![bildschirmfoto 2017-01-24 um 15 45 43](https://cloud.githubusercontent.com/assets/5337809/22252886/fa8dec70-e24f-11e6-9096-0bfd5e1f13bf.png)

**Comment by Rune23** [comment]
I have a better version of number 3: The first time you make a transaction you will be prompted to **set your allowance**

**Comment by pimato** [comment]
UPDATED : 

![bildschirmfoto 2017-01-24 um 21 41 51](https://cloud.githubusercontent.com/assets/5337809/22265818/f5d1063a-e27d-11e6-941e-08989200d405.png)

**Comment by pimato** [comment]
Okay I have a few points : 

- Warning signs should be aligned to the widgets below.
- the number_icon should have the same padding to the left as to the right
- You still have a opacity on the number_icon and the dots, please remove it.

This is how it should look like:
<img width="929" alt="bildschirmfoto 2017-01-31 um 22 39 39" src="https://cloud.githubusercontent.com/assets/5337809/22485757/2513e7e4-e807-11e6-9703-cdf4e35a5ccf.png">


I uploaded you new darker crosses. There is a default(normal) edition and a pressed version. Would love to see both integrated.
[Archiv.zip](https://github.com/makerdao/maker-market/files/743259/Archiv.zip)

**Comment by gbalabasquer** [comment]
@pimato changes were applied in the repository. When this is uploaded please check what you think about the alignment. The structure is a bit complicated and tried to align it the best as possible. Let me know if looks fine.

**Comment by pimato** [comment]
small issue when I am cloing the right warning : 

<img width="942" alt="bildschirmfoto 2017-02-02 um 15 37 35" src="https://cloud.githubusercontent.com/assets/5337809/22553591/97fec6a0-e95d-11e6-9046-fc32ffa01148.png">

**Comment by gbalabasquer** [comment]
@pimato for some reason in your screen the first li fits in one line. The bullet was prepared for two. Will make some tests.

**Comment by gbalabasquer** [comment]
@pimate just made a fix. Let's see if you still see the issue when we upload this.

**Comment by pimato** [comment]
Yes, sadly I can still see it.

<img width="971" alt="bildschirmfoto 2017-02-20 um 21 56 40" src="https://cloud.githubusercontent.com/assets/5337809/23141646/19d19dc0-f7b8-11e6-8d81-06bb46dd316a.png">

**Comment by pimato** [comment]
fixed
