### ISSUE TITLE
Logo is weird

### ISSUE THREAD

**Issue by Rune23** [OasisDEX/oasis#129]
This is what i currently see

![image](https://cloud.githubusercontent.com/assets/10237459/22181352/69e2024e-e0bd-11e6-9850-c71ecf324153.png)

**Comment by gbalabasquer** [comment]
@pimato Do we have a solution for this?

**Comment by pimato** [comment]
@Rune23 we changed the svg to png. Is it good for you now ?

btw. @gbalabasquer could you make it vertical align with the account and the market picker ?

![bildschirmfoto 2017-01-24 um 22 04 19](https://cloud.githubusercontent.com/assets/5337809/22266771/86d661a4-e281-11e6-95e3-807a2ed9f464.png)

**Comment by apmilen** [comment]
I think @cassiopaia has a fix for this

**Comment by pimato** [comment]
@apmilen  : awesome. I also thought that the png isn't looking good comparaable to the SVG version.

**Comment by gbalabasquer** [comment]
@pimato 
Ok let me know when the svg is ready and we will do change it back and work on the alignment. Anyway is strange a png is blurry. Maybe somehting wrong in the export?

**Comment by pimato** [comment]
replaced the logo with a png version!
