### ISSUE TITLE
Allowance Setup has no separator

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#149]
![bildschirmfoto 2017-01-27 um 18 19 07](https://cloud.githubusercontent.com/assets/5337809/22380278/2e7aa68a-e4bd-11e6-87c5-765714ad0678.png)

**Comment by pimato** [comment]
could you change the color of the 

separator to : #E5E9EB
underline of the textfield : #F5F6F6 (same color as the buy/sell widget)

**Comment by gbalabasquer** [comment]
@pimato the separator color is fine.
However I'm checking the color in the buy/sell widget for the border bottom and it is #F7F8F9 not #F5F6F6. Everywhere I'm checking is the same.

**Comment by pimato** [comment]
could you give the Set the same margin-left as in the Textinputfields from the Buy/Sell Widget ? and the text has a bigger gap to the underline compared to the other Textinputfields (like in the Buy/Sell Widget)

<img width="447" alt="bildschirmfoto 2017-02-02 um 15 42 03" src="https://cloud.githubusercontent.com/assets/5337809/22553853/6fca4e06-e95e-11e6-971d-46bf532f9416.png">

**Comment by gbalabasquer** [comment]
@pimato 
With which widget you are comparing the allowance modal and seeing the difference?
With the buy/sell modal or with the paper in the homepage?

**Comment by pimato** [comment]
fixed
