### ISSUE TITLE
Feature Request: Add Real Time Price Feed To Maker Market

### ISSUE THREAD

**Issue by Gronk7** [OasisDEX/oasis#153]
When you buy Maker you know you are getting the market price because Maker is only sold on Maker Market. But because the other tokens are sold on centralized exchanges, and because the centralized exchanges still have all the liquidity, you don't know if you are getting the market price when you are buying them on Maker Market. Obviously the solution is to open Kraken or Poloniex, or some other exchange, to find the current price. However, the user experience would be better, if there was a live price feed from kraken or polo showing the current prices on Maker Market.

**Comment by pimato** [comment]
We are currently not thinking about to show price-feeds from centralised exchanges.
