### ISSUE TITLE
Add VSL (vSlice) token as listed below

### ISSUE THREAD

**Issue by jamesgroton** [OasisDEX/oasis#157]
https://etherscan.io/tokens

**Comment by nanexcool** [comment]
@jamesgroton just need to confirm that VSL uses 18 decimals. It's not stated in the contract.

But looking at this transaction https://etherscan.io/tx/0x20b5b16d8b14f855bbb24a149106f5581078275fc7ba1756d01bb9f40fa07543 it says that 1 VSL token was transfered, and the amount is 1000000000000000000, so I guess it does use 18 decimals.

**Comment by nanexcool** [comment]
Ready for testing at https://maker-market.surge.sh/#trade/W-ETH/VSL

After a bit of testing we'll add them to the main site.

**Comment by nanexcool** [comment]
VSL is live both on OasisPro and OasisLite! (in Pro, scroll down a bit on the Markets box. In Lite just select VSL from the dropdown.

https://pro.oasisdex.com/#trade/W-ETH/VSL

https://oasisdex.com/#trade/W-ETH/VSL

**Comment by pimato** [comment]
VSL token added.
