### ISSUE TITLE
plutus community would like PLU added to the exchange

### ISSUE THREAD

**Issue by jadexoe** [OasisDEX/oasis#160]
The community of the Plutus PLU token would like to be added the maker exchange. As of now the only exchange is used is etherdelta, it has good volume there and most weeks it is the highest volume token traded.

The plutus community has been wishing for a good exchanges to trade on which are decentralised, We did try bit square but because it is manly a bitcoin exchange it did not really work for the ethereum coin holders.

I am sure this will create interest in the community for them too also buy maker token and be more involved in your project..

Thanks

**Comment by jadexoe** [comment]
There has been communication about makerdao on the slack channel by the community and seems that the community has support for maker,    https://plutusitgroup.slack.com

**Comment by nanexcool** [comment]
@jadexoe can you give me PLU's address in the blockchain?

**Comment by jadexoe** [comment]
Contract Address:	0xD8912C10681D8B21Fd3742244f44658dBA12264E

https://etherscan.io/token/pluton#balances

**Comment by jadexoe** [comment]
thank you for the support..

**Comment by CoinManiac1** [comment]
I hope Plutus is added in the maker market. Thanks @jadexoe for requesting for the market for the community

**Comment by nanexcool** [comment]
Ready for testing at https://maker-market.surge.sh/#trade/W-ETH/PLU

After a bit of testing we'll add them to the main site.

**Comment by jadexoe** [comment]
nanexcool, thank you for giving the plutus community a go on your exchange and trade.

**Comment by pimato** [comment]
PLU Token added.
