### ISSUE TITLE
Loading indicator on the Transfer History Paper in the Column Date

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#168]
<img width="480" alt="bildschirmfoto 2017-02-05 um 21 05 40" src="https://cloud.githubusercontent.com/assets/5337809/22629468/f47fb4da-ebe6-11e6-96b3-7d83df52c275.png">

**Comment by peculiarity** [comment]
Fixed in https://github.com/OasisDEX/oasis/pull/269
