### ISSUE TITLE
Specify License

### ISSUE THREAD

**Issue by c055** [OasisDEX/oasis#17]
@jorisbontje:

(ported from [ Specify License #119 ](https://github.com/MakerDAO/maker-otc/issues/119))

**Comment by cassiopaia** [comment]
@rainbeam:

>I think this is important, but I'm not sure how it would work. Some thoughts:

> - Can Maker, as a DAO, hold copyright? (I'm guessing not)

> - Could the collective authors hold the copyright instead? This could be doable with the limited # of contributors.

> - Could nexus / oneup hold the copyright?

> - Do art assets have different copyright? (i.e. cass contribs)

> - Lean towards the initial license being strong copyleft (e.g. AGPL), at least until we figure out a need for something else. Could have scope for exceptions.

**Comment by pimato** [comment]
Apache license 2.0 added.
