### ISSUE TITLE
BTCMACROECON would like to request listing of token at MKR

### ISSUE THREAD

**Issue by btcmacroecon** [OasisDEX/oasis#170]
Token Contract: 0xf77089f2f00fca83501705b711cbb10a0de77628
I would kindly like to request listing BTCMACROECON tokens on MKR to establish a market and work towards issuance for a silly beer drinking game I created. In decentralized fashion I would like to work towards building a dapp to allow people to buy these tokens for the purpose of the game and in the process steer traffic to MKR, the exchange, and to buy my tokens in order to establish circulation and work on value via exchange, in free market fashion.
I am working on establishing a dapp but have a learning curve, but figure first thing is to establish a market for circulation and can work on steering people here, if it would be allowed at all. I see a few tokens but first thing need to ask if it would be ok and if possible. Thanks
The game could be used for any tokens really, fyi. It involves binge drinking. It is utilitarian to the extent that it educates others in how to get MyEtherWallet to start, how to send, (basics in security), how to get set up with Metamask, how to check account, tx transactions via EtherCamp, and steers them into discussion of smart contracts, all while consuming mass quantities. There is value in the educational process and in so doing I need to establish a market and work on a worldwide audience of party animals. I think it's rather unique. First thing is to get them into the game with tokens. google btcmacroecon drinking game for more info (21 squares)
This token is not limited to just the BTCMACROECON Drinking Game

**Comment by pimato** [comment]
Sorry but as there is no way to determine if this is a scam it can't be added for now. What you should do is fork our code and deploy your own oasis contract and frontend, and then market it independently. If you manage to attract an organic community around your project then it will be possible for us to add it to the main OasisDEX frontend.

**Comment by btcmacroecon** [comment]
i think thats a really good idea. I have contacted someone in switzerland
to see if we can get some pairings going including with eth

**Comment by btcmacroecon** [comment]
not a scam but your idea is really good one and i have contacted someone in switzerland to look at some pairings including with eth. Good way to prove and get some volumes in secondary markets if can be established.
