### ISSUE TITLE
Deposit/Withdraw widget should have a 0 in the Amount Inputtextfield.

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#172]
<img width="827" alt="bildschirmfoto 2017-02-08 um 13 44 12" src="https://cloud.githubusercontent.com/assets/5337809/22737760/cd035be4-ee04-11e6-93b5-4d1c7f4fd3d5.png">

**Comment by gbalabasquer** [comment]
Fixed in https://github.com/OasisDEX/oasis/pull/260
