### ISSUE TITLE
include a dropdown on my orders widget to separate from open/closed orders.

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#174]
<img width="492" alt="bildschirmfoto 2017-02-09 um 19 41 16" src="https://cloud.githubusercontent.com/assets/5337809/22797745/c30d87bc-eeff-11e6-9551-fc91987770bc.png">

**Comment by pimato** [comment]
Tasks:

- [ ] Change "My Orders" to "My Trades"
- [ ] Add Dropdown with filter open, closed
- [ ] Show closed buy and sells from user

**Comment by peculiarity** [comment]
I guess we can close this... or we are closing it once it's in production ?

**Comment by pimato** [comment]
yeah, after it is tested for a while... then we are closing it.
