### ISSUE TITLE
minor bugfixes of the repository readme

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#180]
- picture of Maker is broken and should be replaced with the new OASIS logo.

![logo](https://cloud.githubusercontent.com/assets/5337809/23130981/a3ef51b2-f788-11e6-9c8a-326368c3cf2e.png)

- after installing oasis locally I got a few problems which should be mentioned in the Installation (for Developers) process : 
- oasis is not working with solidity 0.4.9 . So a step how to downgrade to 0.4.8 should be appropriate.

one step should be included because I got problem with one package:

To run the frontend, start meteor:

`cd frontend`
`npm install`
`meteor`

**Comment by reverendus** [comment]
Agree, I had to do `meteor npm install` before meteor would start. It's not in the manual

**Comment by pimato** [comment]
fixed
