### ISSUE TITLE
Buy/Sell Widget Inputfields should have placeholders instead of a fixed 0.

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#195]
<img width="466" alt="bildschirmfoto 2017-02-23 um 08 22 40" src="https://cloud.githubusercontent.com/assets/5337809/23248768/6b674780-f9a1-11e6-9d44-5f22e8641d3d.png">

**Comment by gbalabasquer** [comment]
Fixed on https://github.com/OasisDEX/oasis/pull/260
