### ISSUE TITLE
Optimize block scanning for past Trade events

### ISSUE THREAD

**Issue by reverendus** [OasisDEX/oasis#196]
Currently, a block number from which we scan for past Trades is hardcoded in _package-post-init.js_ in the ```Dapple.getFirstContractBlock``` function. It turns out to be difficult to maintain so actually nobody does it. The current value for mainnet (2100636) makes it scan the blocks from the last 6 months, even if the contract has been deployed only a few days ago.

For Ropsten the order history doesn't even load on MetaMask, the backend it uses to fetch archival events times out.

My suggestion is to:
* store the initial block number in the _SimpleMarket_ contract's storage and make it public (or expose with a getter),
* read that block number in Oasis from the contract and start scanning for events from it,
* use some kind of fallback mechanism for old contracts, which do not have that property.

**Comment by reverendus** [comment]
I have also verified that this should solve the problem _rune_ reported regarding Oasis Pro loading terribly slow on his network connection. I've crafted a test version for him (https://reverendus-oasis-pro.surge.sh/) where the only change made was raising the initial block number for mainnet from 2100636 to something very recent (from a few days ago) and _rune_ confirmed that it totally solved his problem.

Of course, it will still be slow for old markets, but fortunately most users won't be browsing them very often I presume.

**Comment by reverendus** [comment]
Actually, solving this issue became part of one of the proposals. What we want to do is implement a lookback mechanism so there is no need to deal with hardcoded block numbers in the frontend nor to keep any block numbers in contract's storage as well.

**Comment by pimato** [comment]
fixed
