### ISSUE TITLE
Order disappeared after "Your order is being placed..."

### ISSUE THREAD

**Issue by Lucas12138** [OasisDEX/oasis#249]
I created new contracts( ICN token and the expiring market) on ropsten testnet. And I have modified the config.addresses.json, changing the related token. However, once I made an buy/sell order, I can only see the ICN token transferred to the expiring market contract(through Mist). On the user interface, the order disappeared after the "Your order is being placed...". Could please tell me how to fix this?

**Comment by peculiarity** [comment]
Can someone verify this one ?
I haven't experience it so far? 
I will close it and if someone has the problem , will create a new one or open this one
