### ISSUE TITLE
Wrap/Unwrap issue

### ISSUE THREAD

**Issue by rmerom** [OasisDEX/oasis#258]
I wrapped 1.1 ETH.

However, on oasis FE I currently only see the history, but not any balance of W-ETH. I'm new to this, maybe I'm not understanding the UI correctly?

![image](https://cloud.githubusercontent.com/assets/650968/25777230/f6a2f826-328b-11e7-83f6-791908682fff.png)

For privacy I prefer not to post the tx details here, but I can DM them if needed.

**Comment by gbalabasquer** [comment]
@rmerom were you've being using metamask? They had/have some issues with their node connections that is why people can not be reflected last changes.
Try to enabling and disabling the plugin again and reload the page and should work.

**Comment by pimato** [comment]
@rmerom is the balance still not showing up ?

**Comment by rmerom** [comment]
Yeah, it got resolved after > 24 hours (closing and reopening the page did not help though)
