### ISSUE TITLE
W-GNT Order

### ISSUE THREAD

**Issue by charlieamadeus** [OasisDEX/oasis#259]
2 w-gnt order filled

https://etherscan.io/tx/0xe916bb3b5ca8db758e40b337eafa6fafac96f9d1add8a689f94b0045dd5249c2

sell w-gnt does not show newly acquired 2 w-gnt

where did the w-gnt go?

![5-7-2017 7-03-09 pm](https://cloud.githubusercontent.com/assets/3020677/25787604/e2557156-3357-11e7-97e7-c3035bc37d59.png)

**Comment by charlieamadeus** [comment]
Well, the w-gnt finally showed up. Looks like it took ~48hrs, is that expected/normal?

**Comment by gbalabasquer** [comment]
@charlieamadeus not really. It seems there was some issue in the network node.
Were you using metamask? That would explain the issue as they've been having problems lately with their nodes.
