### ISSUE TITLE
Transfer widget amount inputfield should have a placeholder instead of real value

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#261]
<img width="460" alt="bildschirmfoto 2017-05-08 um 21 56 07" src="https://cloud.githubusercontent.com/assets/5337809/25822575/44db8e6e-3439-11e7-93cd-475e6c749585.png">

**Comment by systemaddict** [comment]
Yes please. But this goes for all input fields?

Also a "Buy Max" - button (considering gas price as well) would be real nice. I spend too much time changing/rejecting, etc.

**Comment by pimato** [comment]
@systemaddict thank you for your feedback. Regarding the "Buy Max"- button, this is something which will definitely come in the next weeks/months. If you have anything else in mind, please share it with an issue.

**Comment by gbalabasquer** [comment]
Fixed in https://github.com/OasisDEX/oasis/pull/260
