### ISSUE TITLE
Allowance inputfield should have the order amount which is necessary to fill the order.

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#262]
<img width="459" alt="bildschirmfoto 2017-05-08 um 22 47 35" src="https://cloud.githubusercontent.com/assets/5337809/25824620/5f106ad2-3440-11e7-93ec-d1bc23dda77a.png">

**Comment by gbalabasquer** [comment]
Fixed in https://github.com/OasisDEX/oasis/pull/260
