### ISSUE TITLE
If a metamask user is not signed in, we should inform him

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#264]
Currently we are just showing that the account is not found:

<img width="1276" alt="bildschirmfoto 2017-05-10 um 14 29 32" src="https://cloud.githubusercontent.com/assets/5337809/25898609/210e77c6-358d-11e7-84f3-f53f456af4ca.png">

**Comment by gbalabasquer** [comment]
@pimato I'll look at this. Do you want to send me the correct text? and do you think we should make it red to make it very notorious?

**Comment by gbalabasquer** [comment]
Fixed on https://github.com/OasisDEX/oasis/commit/7c295a559c0d8141ff3e94dd1f2441d8db4d908e

**Comment by gbalabasquer** [comment]
@pimato I'm closing this issue.
