### ISSUE TITLE
Replace footer link waffle with our new github project management website 

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#267]
<img width="247" alt="bildschirmfoto 2017-05-12 um 14 13 28" src="https://cloud.githubusercontent.com/assets/5337809/25997679/6a18d498-371d-11e7-9fda-8abd372bfa9d.png">

**Comment by gbalabasquer** [comment]
@pimato which would be the link text?

**Comment by pimato** [comment]
<img width="305" alt="bildschirmfoto 2017-05-16 um 13 28 01" src="https://cloud.githubusercontent.com/assets/5337809/26103824/86769bcc-3a3b-11e7-893a-98478244ffb2.png">
