### ISSUE TITLE
Orders not clearing - has exchange broken down?

### ISSUE THREAD

**Issue by martellalex** [OasisDEX/oasis#283]
Orders do not seem to be clearing on Oasis. 

Looks like the exchange has broken down 😮 

![1981a3ac-d050-4e9e-b9bf-8b4552d133f9](https://cloud.githubusercontent.com/assets/8480779/26387633/759c54e2-4092-11e7-8743-979d89e96810.png)

**Comment by pimato** [comment]
duplicate issue: https://github.com/OasisDEX/oasis/issues/166
