### ISSUE TITLE
UI does not handle meta mask dropping connection

### ISSUE THREAD

**Issue by martellalex** [OasisDEX/oasis#284]
The problem I was encountering was buttons in OasisDEX (e.g. change allowance) not responding.

After clearing cookies, switching computers, adding more ether to Meta Mask, etc. I worked out that OasisDEX was not responding due to losing connection to Meta Mask.

See screenshot for the error as per the Chrome console.

I found it took a few refreshes for the connection to stabilise and actions like wrapping/unrwapping, trades etc. would only work if I did not see this error.

One quick fix I guess might be an alert if the connection to meta mask is dropped.

![image](https://cloud.githubusercontent.com/assets/8480779/26387898/8cfd527e-4094-11e7-965d-48987ad84a09.png)

**Comment by pimato** [comment]
seems like a metamask problem
