### ISSUE TITLE
Expand the Inputfield to fill the box they are in

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#289]
Currently only half of the inputfield-box is clickable. The whole box should be clickable:

<img width="461" alt="bildschirmfoto 2017-05-27 um 13 48 02" src="https://cloud.githubusercontent.com/assets/5337809/26521211/2fd13fa6-42e3-11e7-8af5-3d8a8536f8ee.png">

**Comment by peculiarity** [comment]
This has been done for order matching
