### ISSUE TITLE
Remove unnecessary message on the buy/sell widget

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#295]
We don`t need it anymore, because the order matching will get you the best offer anyway:

<img width="468" alt="bildschirmfoto 2017-06-03 um 12 48 15" src="https://cloud.githubusercontent.com/assets/5337809/26752934/4f682fc8-485b-11e7-85b1-1dc4807dc9b5.png">

**Comment by peculiarity** [comment]
Actually we need it if we have buy() available.
