### ISSUE TITLE
Oasis Wrapping Transaction Still Pending After 22mins

### ISSUE THREAD

**Issue by ChurchOfNotNothing** [OasisDEX/oasis#299]
I've got the etherscan
https://etherscan.io/tx/0xb45322893287dbe1d16b51f8258aa7d31f5577b1150fffff16dc10762e472d23

It is crazy....been on here before without an issue. Now the transaction is in limbo????

**Comment by pimato** [comment]
It looks like your transaction went through. There is a high chance that Metamask and the provided Infura nodes are problem. We know that, so we are providing our own rpc/server for connecting to the Ethereum Blockchain. The Address is : http://rpc.makerdao.com:7777, you can add it via Metamask here : 

<img width="371" alt="bildschirmfoto 2017-06-08 um 11 46 46" src="https://user-images.githubusercontent.com/5337809/26922718-324b5e5e-4c40-11e7-9a61-0fc6e89ad079.png">
