### ISSUE TITLE
Unwrap issue

### ISSUE THREAD

**Issue by britcruise9** [OasisDEX/oasis#301]
Unwrap never passes the confirmation step - I've tried 3 times

![screen shot 2017-06-10 at 2 36 06 pm](https://user-images.githubusercontent.com/29343479/27006515-44f6279a-4dea-11e7-8913-a8a44ceadd66.png)

any help?

**Comment by pimato** [comment]
Issue is related to: https://github.com/OasisDEX/oasis/issues/302
