### ISSUE TITLE
Allowance stuck

### ISSUE THREAD

**Issue by britcruise9** [OasisDEX/oasis#302]
I've been unable to update my allowance beyond zero - it seems stuck on "pending" - advice?

![screen shot 2017-06-10 at 2 41 19 pm](https://user-images.githubusercontent.com/29343479/27006528-f4d56d60-4dea-11e7-9f78-bae32bbbfd3c.png)

**Comment by pimato** [comment]
1) Are you using metamask ?
2) Which node ?

**Comment by britcruise9** [comment]
yes I am, and on the ethereum mainnet

**Comment by pimato** [comment]
alright next:

If you still have problems changing your allowance you could 

1) try to restart the metamask extension via the extension settings.
2) use our community rpc http://rpc.makerdao.com:7777

**Comment by britcruise9** [comment]
Thanks - I joined your rpc, and I receive this error 

![screen shot 2017-06-12 at 9 40 54 am](https://user-images.githubusercontent.com/29343479/27044729-796d63ca-4f53-11e7-96a1-28bee3708fe2.png)

I also tried going back to the mainnet and now all of the buttons are inactive.

standing by

**Comment by pimato** [comment]
could you contact me via chat.makerdao.com, so I can help you out instantly. (Just pm me)

**Comment by britcruise9** [comment]
thanks, just tried it on firefox and problem solved :)

**Comment by pimato** [comment]
if you need instant help, please join our community via chat.makerdao.com
