### ISSUE TITLE
Lost ETH

### ISSUE THREAD

**Issue by jonathanmarcus** [OasisDEX/oasis#310]
Hello.

I deposited ~ 1.5 ETH into Oasis (https://cl.ly/1x2c0X3B2O3O) on 06/25/17: https://etherscan.io/tx/0x2dbf20cf516b8af750f0e9553e5684e380e5df557b8f97af0e80f1deb417c688

The ~ 1.5 ETH appeared in the Wrap section (https://cl.ly/1t2h2R110x29) for about a day. I tried to wrap the ETH unsuccessfully several times throughout the day. The wrap progress meter kept hanging after it said the wrap was complete.

After about a day (I don't remember the exact timeline), I went to Oasis to re-try wrapping the ETH, and the balance was zero. There is ~.49 ETH of wrapped ETH in my account from several weeks ago.

Is there anything I can do to recover the ETH? I just want to buy MKR and have run into all sorts of technical issues :(

Thanks - Jonathan.

**Comment by pimato** [comment]
Hey Jonathan.

So my first question is: 

1)  You provided a link from etherscan where you transfer ETH from an address to another address. Are you using both addresses : 

a) 0xc4dd5d67bc306c7b8e3ef3a27a86b5dfe9b9e2c8
b) 0xff536328697859ec41b4f6a7e3a9cc3f372b0760

**Comment by pimato** [comment]
If you still have questions, please reopen the issue.
