### ISSUE TITLE
Issue with ETH-MKR order

### ISSUE THREAD

**Issue by bugbitez** [OasisDEX/oasis#312]
I am having issues with a recent order. I'm running metamask, and was able to wrap my ETH no problem. But whenever I tried to make a buy order, the default gas/gwei would give me a "nonce too low" every attempt. Thought it was a parity error and finally got an order in today. I saw my W-ETH has left my wallet, but my trade history both open/closed show nothing, and no MKR in my account either (but an Erc20 Token in my transfer tabs on etherscan?) Is my buy order just incomplete and won't appear until it is, or misplaced?

**Comment by peculiarity** [comment]
Can you give more details - txhash, parameters of the order and etc?

**Comment by bugbitez** [comment]
My problem seems to have resolved, or at least now my trade appears under Open history. Thanks for the prompt response though.
