### ISSUE TITLE
Account visualisation bug 

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#314]
After loading http://matcher.oasisdex.surge.sh/#trade/MKR/W-ETH 

My Account visualisation is changing from: 

<img width="486" alt="bildschirmfoto 2017-07-07 um 22 13 19" src="https://user-images.githubusercontent.com/5337809/27975419-5d60f0e8-6362-11e7-9a29-45ba28a3851d.png">

to

<img width="477" alt="bildschirmfoto 2017-07-07 um 22 12 51" src="https://user-images.githubusercontent.com/5337809/27975424-637771e6-6362-11e7-9c64-70d0d1dc38fd.png">

**Comment by peculiarity** [comment]
1st It makes no sense , since there hasn't been change anything.
2nd How many times did you get it ?

**Comment by pimato** [comment]
solved by https://github.com/OasisDEX/oasis/pull/304
