### ISSUE TITLE
Loading orders when chain out of date goes over 100%

### ISSUE THREAD

**Issue by joeykrug** [OasisDEX/oasis#315]
<img width="130" alt="screen shot 2017-07-09 at 5 58 02 pm" src="https://user-images.githubusercontent.com/5925937/27999567-7011fc60-64d3-11e7-9888-2a0ad8981c23.png">

See screenshot ^

**Comment by peculiarity** [comment]
No worries, this has been fixed but currently it's not deployed. Thank you for the report though!
