### ISSUE TITLE
Remove "wrap max" option

### ISSUE THREAD

**Issue by livnev** [OasisDEX/oasis#319]
On the Wrap/Unwrap tab, when wrapping ETH, a "Wrap Max" button comes up, suggesting that the user wraps all ETH in the account. While this type of button is helpful in other contexts like Unwrap and Transfer, wrapping all of your ETH leaves you with no ETH for gas to do any other transaction (including Unwrap), which is almost never what the user will want, so IMO suggesting this with the UI is not user-friendly.

**Comment by livnev** [comment]
I checked and this is still an issue on the order matching branch (or at least on whatever is deployed to matcher.oasisdex.surge.sh).

**Comment by peculiarity** [comment]
@pimato  Can you check this one. @livnev  has a point on that. Or probably we can have it but instead of filling absolutely everything , we can leave 1 ETH just in case. What do you think ?

**Comment by pimato** [comment]
@peculiarity I think 1 ETH is too much, not everyone has so much ETH on their wallet. What do you think about something like this ? Should we set a limit of 0,005 ? 

<img width="436" alt="bildschirmfoto 2017-09-11 um 23 18 21" src="https://user-images.githubusercontent.com/5337809/30279229-9a64cdca-9747-11e7-80a3-3d50001aed26.png">

With that the wrap max button could stay, but we would remove the limit amount which should stay in the wallet.

**Comment by peculiarity** [comment]
Why not .. 1 ETH was used to point out the idea.

**Comment by livnev** [comment]
Personally I am not a fan of this fix. The reasons are:

1. I don't think Oasis and the rest of the ecosystem are ready<sup>1</sup> to have the concept of W-ETH abstracted away completely, so it's better to force the user to have a clear understanding of the difference between ETH and W-ETH at the earliest stage instead of getting in trouble later.
2. I don't like the idea of arbitrarily choosing some constants on behalf of the user

Doing a simple mental subtraction to leave some ETH for gas is not that hard. If anything, there should be a big warning sign that says not to wrap all of your ETH lest you leave nothing to pay for gas.

<sup>1</sup> - my understanding is that eventually (post-Metropolis) W-ETH will no longer be needed, so we probably don't need to take a super long-term view on this issue.

**Comment by pimato** [comment]
@livnev thanks for your input. I will instead create a warning sign like you recommended because we do not want to decide on behalf of the user.

**Comment by pimato** [comment]
Current version:
<img width="887" alt="bildschirmfoto 2017-09-15 um 11 49 02" src="https://user-images.githubusercontent.com/5337809/30464318-e60d8980-9a0b-11e7-87b8-0b9e5d44101d.png">

Question:
Should we make the warning message red?

**Comment by kennyrowe** [comment]
The message could be red and dripping diamonds a people will still miss it, but it's probably worth doing.

I agree with @livnev we should also remove the `Max Wrap Button` or modify it to leave some left over for gas cost.

**Comment by pimato** [comment]
@kennyrowe thanks a lot for your input. I updated the warning sign accordingly.

<img width="551" alt="bildschirmfoto 2017-09-15 um 14 17 40" src="https://user-images.githubusercontent.com/5337809/30467595-b0d75416-9a20-11e7-836d-d94af8f90788.png">

**Comment by NiklasKunkel** [comment]
I agree we should get rid of the "Wrap Max" button. Choosing arbitrary constants for the user is confusing. I think the red message text with the warning is a good idea. It will educate users on how Oasis (an dapps in general work) and protects them from the situation where they have wrapped all of their ETH and can't even pay to unwrap it.

**Comment by peculiarity** [comment]
Well they can't wrap all of the ETH anyways because wrapping needs ETH :)

**Comment by kennyrowe** [comment]
This looks pretty great to me @pimato

**Comment by peculiarity** [comment]
Actually you can see it  at dev.oasisdex.surge.sh . We agreed no have the warning message as static , not on click.:)

**Comment by peculiarity** [comment]
Fixed in #336
