### ISSUE TITLE
Add trade date/time to "My Trades > Closed"

### ISSUE THREAD

**Issue by livnev** [OasisDEX/oasis#320]
Being able to access date/time is very useful for record keeping. Date/time is shown on "Market History" but not in "My Trades > Closed". So I need to do a lot of searching in "Market History" to find the date/time of my past trades, which is inconvenient. I see no reason why "My Trades > Closed" can't have date/time in the left column.

**Comment by peculiarity** [comment]
@pimato any thoughts?

**Comment by pimato** [comment]
@livnev @peculiarity agreed!

**Comment by peculiarity** [comment]
Do we want to have the date only for close  or we c an have them for opened as well?
