### ISSUE TITLE
Setting max allowance breaks popup windows

### ISSUE THREAD

**Issue by livnev** [OasisDEX/oasis#322]
Setting your allowance very high, e.g. as high as it can go (`2**256 - 1`) breaks the popup boxes, screenshot below:

![oasis_allowance](https://user-images.githubusercontent.com/3964494/29071536-f8218c0e-7c3b-11e7-9a16-fbdf7480c219.png)

There has been discussion of using this trick of setting the allowance super high for better UX and to avoid wasting gas, unfortunately it has this nasty side effect.

**Comment by jpritikin** [comment]
Can Maker controlled ERC20 tokens be pre-authorized to be manipulated by Maker contracts? It seems like this could be implement for at least SAI, SKR, DAI, MKR, and maybe W-ETH. I'm not sure about W-ETH because W-ETH might be positioned as a token that could be shared with other projects.

**Comment by livnev** [comment]
@jpritikin 

> Can Maker controlled ERC20 tokens be pre-authorized to be manipulated by Maker contracts? It seems like this could be implement for at least SAI, SKR, DAI, MKR, and maybe W-ETH. I'm not sure about W-ETH because W-ETH might be positioned as a token that could be shared with other projects.

I'm not sure if this is a good idea, because:

(i) it would require ALL users of those tokens to trust ALL Maker contracts. Right now you could (in theory) trade MKR or SAI on any venue without trusting the security of Oasis at all, or trade W-ETH on Oasis without trusting the security of any of the Sai/Dai contracts at all. If any single contract on the whitelist had a security issue, all Maker-related tokens could be vulnerable.

(ii) the contract whitelist can only be updated with a token redeploy (I think?), so it would quickly become out of date anyway as new contracts appear in the ecosystem.

**Comment by jpritikin** [comment]
> trade W-ETH on Oasis without trusting the security

Yes, for W-ETH, I agree that maybe the allocation step is appropriate.

> (i) it would require ALL users of those tokens to trust ALL Maker contracts.

But this is mostly true already. The value of Maker tokens are to a large extent contingent on Maker contracts working correctly. Or look at it another way: Suppose we go with the current status quo and require each account holder to allocate tokens to Maker. What if some Maker contract is found faulty. We can't wait for all token holders to change their allocation to zero. The Maker contract needs to be locked somehow to protect the ecosystem. But if we have to do that anyway, what's the point of setting the allocation? Why not just automatically authorize Maker to manipulate Maker tokens?

> (ii) the contract whitelist can only be updated with a token redeploy (I think?), so it would quickly become out of date anyway as new contracts appear in the ecosystem.

Isn't this a question of who has authority to do what? Maybe the whitelist can be controlled by some multisig or whatever. That's an open design question.

**Comment by livnev** [comment]
@jpritikin 

Remember that paranoid users can still set their allocation manually to a small number, if they are using a (new?) contract that they don't trust fully yet (and I think ideally there should remain UI options to do so, in any case you can do this manually by calling `approve()` yourself). With an `approve()` whitelist they will lose the freedom to take such precautions.

> Isn't this a question of who has authority to do what? Maybe the whitelist can be controlled by some multisig or whatever. That's an open design question.

It's not just a design question: your proposal would be a massive centralization step IMO. Giving someone the right to add to the `approve()` whitelist is equivalent to handing them complete control of all tokens (they could approve themselves and take control of your tokens).

**Comment by jpritikin** [comment]
@livnev OK, maybe my idea is not viable.
