### ISSUE TITLE
Market History Widget rounding bug

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#324]
![oasis_display_bug](https://user-images.githubusercontent.com/5337809/29619923-8e473aba-8846-11e7-86f2-da4701dee2fb.png)

**Comment by livnev** [comment]
Here is one of the faulty txs:
https://etherscan.io/tx/0xf51a5861712a0355b58a03c5235aa47d14ab0db4826ab3a8877180d4edce5f15

**Comment by livnev** [comment]
This is fixed in the order matching branch.
