### ISSUE TITLE
"My Orders" display formatting bug

### ISSUE THREAD

**Issue by livnev** [OasisDEX/oasis#337]
![oasisbug](https://user-images.githubusercontent.com/3964494/30784105-4c352308-a146-11e7-91d2-49ad2b214ff4.png)

**Comment by peculiarity** [comment]
Ok managed to reproduce the problem. It comes with the scroll appearance. On my way of fixing it.

**Comment by peculiarity** [comment]
![image](https://user-images.githubusercontent.com/23715025/30801381-5d4cbf8c-a1e3-11e7-99d6-002bdc7042f8.png)

![image](https://user-images.githubusercontent.com/23715025/30801390-66c15b7c-a1e3-11e7-92d5-24ad8a650d15.png)
