### ISSUE TITLE
My Allowance Popup small UI issues

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#340]
The description of the inputfields are not aligned properly:

**bad**:
<img width="451" alt="bildschirmfoto 2017-10-02 um 07 41 24" src="https://user-images.githubusercontent.com/5337809/31065403-4f7c3fa6-a745-11e7-9782-e7b0ace1e8f7.png">

**good**:
<img width="395" alt="bildschirmfoto 2017-10-02 um 07 41 43" src="https://user-images.githubusercontent.com/5337809/31065395-44bab5c0-a745-11e7-9908-40d733bf4cb5.png">

another thing is, the inputfield should be everywhere clickable:

<img width="378" alt="bildschirmfoto 2017-10-02 um 08 09 01" src="https://user-images.githubusercontent.com/5337809/31065904-197d34a6-a749-11e7-80d9-c5fb1f677d78.png">

As soon as the allowance popup is visible, there is a 0 in the inputfield which is not an placeholder. This should be also changed to an placeholder.

**Comment by peculiarity** [comment]
I hope this is ok 
![image](https://user-images.githubusercontent.com/23715025/31167605-e430974c-a8f2-11e7-9dac-578657089b23.png)

**Comment by peculiarity** [comment]
Actually there shouldn't be 0. We have to elaborate on this. usually you go to allowance modal through offer modal. The allowance value is actually the value taken from the offer modal for a given token.

**Comment by pimato** [comment]
<img width="458" alt="bildschirmfoto 2017-11-16 um 13 42 30" src="https://user-images.githubusercontent.com/5337809/32891754-1ad30f0c-cad4-11e7-9396-fca50fb47aad.png">

at oasisdex.com we still don`t have the whole inputfield clickable.

**Comment by pimato** [comment]
same should be done with the transfer widget:

<img width="408" alt="bildschirmfoto 2017-11-16 um 14 05 52" src="https://user-images.githubusercontent.com/5337809/32892664-4c699b14-cad7-11e7-871f-1fac49c5f24c.png">

**Comment by pimato** [comment]
fixed by PR: https://github.com/OasisDEX/oasis/pull/361
