### ISSUE TITLE
Minor Issues on all Widgets

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis#341]
After we pushed a few stuff something which shouldn`t be changed got changed:

<---- left picture is how it **was**___________________right picture how it is **now** ----->

<img width="991" alt="bildschirmfoto 2017-10-02 um 08 29 07" src="https://user-images.githubusercontent.com/5337809/31066271-fabbbab2-a74b-11e7-9d2e-5021a5ab304c.png">

This is the chart widget, but the transfer widget has also the same problems.

<---- left picture is how it **was**___________________right picture how it is **now** ----->

<img width="1029" alt="bildschirmfoto 2017-10-02 um 08 33 53" src="https://user-images.githubusercontent.com/5337809/31066336-76970f56-a74c-11e7-9b7d-c2851a4f131f.png">

literally every widget got changed. I think the last update with the new warning message changed a few things.

**Comment by peculiarity** [comment]
It changed everything because you want a lot of information in small height window. Go check your mockup .

**Comment by peculiarity** [comment]
@pimato  What are we doing with this one?

**Comment by pimato** [comment]
After adding the new Create DAI Button there are still some flaws in the UI implementation:

- The Button should have the same padding-right and padding-top as in the CHART widget.

<img width="1104" alt="bildschirmfoto 2017-11-16 um 13 36 27" src="https://user-images.githubusercontent.com/5337809/32891587-6a7d5220-cad3-11e7-9021-58cc6a7a75ef.png">

**Comment by pimato** [comment]
fixed with commit: 0272c11fd53792b09d74150fb6cdff72b58273d9 and 57e807dae5b243b36edb8398252969464bcf4954
