### ISSUE TITLE
Trouble loading: Price, history and charts

### ISSUE THREAD

**Issue by MadsGrenaa** [OasisDEX/oasis#347]
Using Mac and Chrome, assessing through MetaMask (logged in)

The issue have been coming and going over a longer period, and I can't seem to find any consistency in when Oasis is unable to load the three items. They seem to be loading into infinity.

I have tried using the Maker RPC through MetaMask but with no change.

I never have trouble loading offers.

I have attached screenshots per Geronimos recommendation 
![screen shot 2017-10-25 at 23 06 56](https://user-images.githubusercontent.com/27723090/32023810-b66c355c-b9da-11e7-96d7-e0ef6e8c4697.png)
![screen shot 2017-10-25 at 23 00 36](https://user-images.githubusercontent.com/27723090/32023811-b689a6d2-b9da-11e7-8ea1-5887d73f0ee0.png)
![screen shot 2017-10-25 at 23 00 26](https://user-images.githubusercontent.com/27723090/32023813-b6a5b66a-b9da-11e7-9196-c005b05e442b.png)

**Comment by peculiarity** [comment]
@MadsGrenaa  the error you posted , are not affecting the loading of the given items. Good you've included though and thanks for that. 

Can you please verify if you experience the same issue? Also would be nice to give versions of the metamask plugin and the browser and etc.

Cheers

**Comment by MadsGrenaa** [comment]
The problem have vanished and I have no idea why, so closing the issue.
