### ISSUE TITLE
Incorrect Closing Time

### ISSUE THREAD

**Issue by JerryMichels** [OasisDEX/oasis#364]
Hi - browsed through the existing issues before creating this. The closing time seems to display a date in the past (see screenshot). Not sure what the date is meant to indicate but I would have expected the current date + time that the exchange would be closed.

![image](https://user-images.githubusercontent.com/6192431/33140768-eb18ad9e-cf7e-11e7-8691-504c2b02ee78.png)

**Comment by NiklasKunkel** [comment]
There's no problem here. The market was deployed on September 11, 2017 and was set to expire a year from that date.
