### ISSUE TITLE
Project idea: cryptofresh page for MKR

### ISSUE THREAD

**Issue by jorisbontje** [OasisDEX/oasis#39]
http://cryptofresh.com/

This would allow MKR to be put up on coinmarketcap.com

**Comment by Rune23** [comment]
It would also be really cool if we could get a page where people can view the MM orderbook without having an active client.

**Comment by Riverhead** [comment]
I'll send this to roadscape (Tim) who created cryptofresh.

**Comment by pimato** [comment]
not necessary because we have api.mkr.market.
