### ISSUE TITLE
mkr.market with light client

### ISSUE THREAD

**Issue by jorisbontje** [OasisDEX/oasis#49]
> bug report: when I make an order on http://mkr.market, after a minute it says "Contract Execution Failed" and doesn't show the order; however, when I check etherscan everything looks fine, and when I reload the dapp everything looks fine and I see the order

**Comment by jorisbontje** [comment]
https://github.com/zsfelfoldi/go-ethereum/wiki/Light-Client-Public-Test

**Comment by pimato** [comment]
Closed as an exact duplicate of https://github.com/OasisDEX/oasis/issues/210
