### ISSUE TITLE
Access previous maker-otc contracts?

### ISSUE THREAD

**Issue by nanexcool** [OasisDEX/oasis#90]
In EtherDelta you can change to previous contracts with a dropdown, in case you want to withdraw tokens from previous versions of contracts.

![image](https://cloud.githubusercontent.com/assets/52510/20795404/bccb8606-b7af-11e6-8c45-e73c1b8e29be.png)

Maybe something like this? Is there a function in maker-otc to cancel every buy/sell order in one go?

**Comment by pimato** [comment]
Do we still want to have this feature implemented ? @Rune23 @apmilen

**Comment by nanexcool** [comment]
Now that we're deploying market contracts that expire in a year, I don't know if it's worth the effort.

**Comment by pimato** [comment]
I also don't think it is necessary anymore. With that I am closing the issue.
